name: vnote
description: vnote starter template
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  #Firebase packages
  flutterfire_ui: ^0.3.1
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  firebase_auth: ^3.3.5
  #Http request
  http: ^0.13.4
  #offline notes save
  sqflite: ^2.0.2
  path_provider: ^2.0.8
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  #dependency injection
  get_it: ^7.2.0
  google_fonts: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.3


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_foreground: true
  image_path: "assets/images/icon_round.png"
